/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger'
import { Group } from 'three'

export function Model(props) {
  const group = useRef<Group>(null)
  const { nodes, materials } = useGLTF('/controller.glb')
  
  useLayoutEffect(() => {
    if (!group.current) return;

    const parts = group.current.children[0].children[0].children;
    
    // Reset positions
    parts.forEach(part => {
      part.userData.initialPosition = { ...part.position };
    });

    // Create timeline for disassembly effect
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#scroll-wrapper",
        start: "top top",
        end: "bottom bottom",
        scrub: 1,
        snap: 1 / (3 - 1),
      }
    });

    // Disassemble on first scroll
    tl.to(parts[0].position, { x: "+=1", y: "+=0.5", z: "+=0.5" }, 0)
      .to(parts[1].position, { x: "-=1", y: "+=0.5", z: "-=0.5" }, 0)
      .to(parts[2].position, { x: "+=0.8", y: "-=0.5", z: "+=0.3" }, 0)
      .to(parts[3].position, { x: "-=0.8", y: "-=0.5", z: "-=0.3" }, 0)
      .to(parts[4].position, { x: "+=0.5", y: "+=0.8", z: "-=0.5" }, 0)
      // Reassemble on second scroll
      .to(parts.map(part => part.position), {
        x: parts.map(part => part.userData.initialPosition.x),
        y: parts.map(part => part.userData.initialPosition.y),
        z: parts.map(part => part.userData.initialPosition.z),
      });

    return () => {
      tl.kill();
    };
  }, []);

  return (
    <group ref={group} {...props} scale={100} dispose={null}>
      <group position={[0, 0.002, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Base1_Back_Baseq_0.geometry}
            material={materials.Back_Baseq}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Base1_Front_Base_0.geometry}
            material={materials.Front_Base}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Base1_Gold_Plates_Below_0.geometry}
            material={materials.Gold_Plates_Below}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Base1_Thumb_Top_0.geometry}
            material={materials.Thumb_Top}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Front_Panel1_Front_Panel_0.geometry}
            material={materials.Front_Panel}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Front_Panel_Box1_Emmissive_0.geometry}
            material={materials.Emmissive}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Ref_Charger_stick1_Port_0.geometry}
            material={materials.Port}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Side_Buttons1_SPCB_0.geometry}
            material={materials.SPCB}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joystick2Top_Trigeers1_Trigger_Buttons_0.geometry}
            material={materials.Trigger_Buttons}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube2_FBCB_0.geometry}
            material={materials.FBCB}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface113_Buttons_0.geometry}
            material={materials.Buttons}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface114_Side_Panels_0.geometry}
            material={materials.Side_Panels}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface115_Transparent_0.geometry}
            material={materials.Transparent}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PS_logoJoystick3_Logo_0.geometry}
            material={materials.Logo}
            position={[2.315, -0.572, -0.016]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere8_Default_Material_0.geometry}
            material={materials.Default_Material}
            position={[2.315, -0.572, -0.016]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/controller.glb')